# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0593773072d932cd106cda5a824f9953fb31ab9c3683f2b6f90a236472feab8e7e92c52fafca165c71f356cba7cc3ffa691730abd1c5a8bf370c78f9c8b92d2

test:
  secret_key_base: 7e25d0b40fac003560a600ec783b7c796666858cbe4119e91ee05ebaa02cce823d3cfa94b9097048bf349a8f361ecb2ba62f9311eb9cea1b572f4c2222c7d3be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
