# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d495ff131e7a3b00f8f74f60733fed498024948a725f244fb0c4c93810830e40c851eccbb6929cbb234784b3249a6439846cc189040790e4fbda8bdb4a3da701

test:
  secret_key_base: eef9f3d414f751c5ac5364b56823ff07f61d0f28b1b1c2733f9cb42f5b2ee1bb52561210c692d9fb21667fda57876d3bf25ad10abc49180519bb128d8551e853

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
