# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2cebc92c8d0050b85dc3a1fca778cf3e3fc9098a33efc6dbc4d581ac71dc5ec12f3bca905bb298126586eb40b4ab36411b695a533ba1bb9417be8042a23b859

test:
  secret_key_base: 8582c967a91ef29e72aff8c930ee03961acba38c30afd1f1ba2f09fb6b271d6d999b7c2c21d8217f774ea386cd07ef264cfbdb8444e74e2bc992c640c6313052

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
