# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0742c0666b8d4523c844752e492528522b33006cce46ce9b1f17568446dfdf8d483468c64c48041a442ee6ef42a06b69927e6c1b4812d935e800b1a9e53eb2d

test:
  secret_key_base: 634d28bfcfccbbbd5e1e6a84951a4b812f03fec50380c163113014b4ddcb3c4cd400f1ad839c3c8bec6bda99f640f3ae6c03912f90eb373e5fb9e83e4ed23704

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
