# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d8f2adfada3e419576e6a73ac5e0b8bd4d494b20a9f9848b658c08a618612ab52870831cf9deab4f5560977e979644ac66336aeaa8bad4cd8e1eb31be56ce79

test:
  secret_key_base: f5ad50c2e0d4877cfa5587d0bf92f0f9e3f750bf3f8ef80404cbaf940ebce40b0436bf9851100ad3d1fd2356bf19ee2b09bc6d79465a1efb133a993d705fd168

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
