# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f3e2ef408f223eb368833df3551921cced7d92bb77f9757dd5a65f6020534e1673638e0c2283d6afe95ab6318ec1b511f70f5896ee0b321ae646e755c6bb538

test:
  secret_key_base: 4d1db888ddc37bafe8d42346b3c9e9dbb489d2bac4c7f1f232bf8b993212c05c5217a047737bdaa8427da2fb0648aed1636c6f82a021bed560c5361438148d3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
